version: "3.3"
services:
    pitorrentbot:
        container_name: torrentbot_run
        image: pitorrentbot:latest
        volumes:
            - /media/hdd/torrents/complete:/transmission/complete
            - /media/hdd/torrents/incomplete:/transmission/incomplete
        network_mode: host
